services:
    ################################################
    #             State                            #
    ################################################
    task_stock.task_state_handler_builder:
      class: Sokil\TaskStockBundle\State\TaskStateHandlerBuilder
      arguments:
        - ~

    ################################################
    #             Single page application          #
    ################################################
    task_stock.spa.controller:
      class: Sokil\FrontendBundle\Controller\IndexController
      arguments:
        - 'TaskStockBundle:Spa:index.html.twig'
        - '@task_stock.spa.app_data'
      calls:
        - [setContainer, ["@service_container"]]

    task_stock.spa.app_data:
      class: Sokil\FrontendBundle\Spa\ApplicationData

    task_stock.spa.app_data_provider.locale:
      class: Sokil\FrontendBundle\Spa\LocaleApplicationDataProvider
      arguments:
        - '@request_stack'
      tags:
        - {name: frontend.spa.app_data_provider, app_data: task_stock.spa.app_data}

    task_stock.spa.app_data_provider.container_parameters:
      class: Sokil\FrontendBundle\Spa\ParameterApplicationDataProvider
      arguments:
        - '@service_container'
        - ["locales"]
      tags:
        - {name: frontend.spa.app_data_provider, app_data: task_stock.spa.app_data}

    task_stock.spa.app_data_provider.csrf:
      class: Sokil\FrontendBundle\Spa\CsrfApplicationDataProvider
      arguments:
        - '@security.csrf.token_manager'
        - common
      tags:
        - {name: frontend.spa.app_data_provider, app_data: task_stock.spa.app_data}

    ################################################
    #            Notifications                     #
    ################################################
    task_stock.task_notification_listener:
        class: Sokil\TaskStockBundle\EventListener\TaskNotificationListener
        arguments:
            - '@notification.schema_provider'
            - '@notification.transport_provider'
            - '@notification.message_builder_collection.task_stock'
        tags:
            - {name: kernel.event_listener, event: task.change}

    task_stock.message_builder.taskChange:
      class: Sokil\TaskStockBundle\Notification\Message\TaskChangeMessageBuilder
      arguments:
        - '@templating'
        - '@translator'
        - '@task_stock.text_diff_renderer.colour'
        - '@task_stock.task_state_handler_builder'
      tags:
        - {name: 'notification.message_builder', messageType: 'taskChange', collectionName: 'task_stock', transport: 'email'}

    ################################################
    #             Voters                           #
    ################################################
    task_stock.voter.task_voter:
        class: Sokil\TaskStockBundle\Voter\TaskVoter
        arguments:
          - '@security.access.role_hierarchy_voter'
          - '@task_stock.voter.task_project_voter'
        tags:
           - { name: security.voter }

    task_stock.voter.task_project_voter:
        class: Sokil\TaskStockBundle\Voter\TaskProjectVoter
        arguments:
          - '@security.access.role_hierarchy_voter'
        tags:
           - { name: security.voter }

    ################################################
    #             Serializers                      #
    ################################################
    task_stock.task_normalizer:
      class: Sokil\TaskStockBundle\Serializer\Normalizer\TaskNormalizer
      arguments:
        - '@task_stock.repository.task_category_schema'
        - '@task_stock.task_state_handler_builder'
        - '@security.authorization_checker'
        - '@translator'
        - %locale%

    task_stock.task_category_normalizer:
      class: Sokil\TaskStockBundle\Serializer\Normalizer\TaskCategoryNormalizer
      arguments:
        - '@task_stock.task_state_handler_builder'
        - %locales%

    task_stock.task_project_normalizer:
      class: Sokil\TaskStockBundle\Serializer\Normalizer\TaskProjectNormalizer
      arguments:
        - '@task_stock.repository.task_category_schema'
        - '@task_stock.task_state_handler_builder'
        - '@security.authorization_checker'

    ################################################
    #             Repositories                     #
    ################################################
    task_stock.repository.task_project:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
        - 'TaskStockBundle:TaskProject'

    task_stock.repository.task_category_schema:
      class: Doctrine\ORM\EntityRepository
      factory: ['@doctrine.orm.default_entity_manager', getRepository]
      arguments:
        - 'TaskStockBundle:TaskCategorySchema'

    ################################################
    #             Others                           #
    ################################################

    task_stock.validation_errors_converter:
        class: Sokil\Converter\ValidationErrorsConverter

    task_stock.attachments_upload_handler:
        class: Sokil\Upload\Handler

    task_stock.text_diff_renderer.colour:
      class: Sokil\Diff\Renderer
      arguments:
        - {format: '%task_stock.diff_renderer.format_colour%'}
